name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allow manual trigger from Actions tab

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: |
          curl --silent --show-error --fail https://shamimtitanic.streamlit.app || echo "App unreachable"
